### ISSUE TITLE
allow webhook subscribers to choose what to subscribe to

### ISSUE THREAD

**Issue by graingert** [jenkinsci/outbound-webhook-plugin#11]
currently the only way to configure outbound hooks is to

> Add Outbound Webhook notification to Post-build Actions:

However devices should be able to subscribe to various events out of the box, eg with an HTTP put request

**Comment by graingert** [comment]
eg moving to a pull model rather than a push model

**Comment by tylerlong** [comment]
> eg moving to a pull model rather than a push model

It sounds like a feature request to Jenkins.

This plugin only focuses on outbound WebHook.
